name: SubstraceTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd richard-test
        cargo build --verbose
    - name: Install my crate
      run: |
        cd richard-test
        cargo install richard-test
        richard-test
