name: SubstraceTest
description: Substrace test action

env:
  CARGO_TERM_COLOR: always

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v3
  - name: Install and run my crate
    run: |
      cargo install richard-test
      richard-test
    shell: bash
