name: SubstraceTest
description: Substrace test action

env:
  CARGO_TERM_COLOR: always

runs:
  using: "composite"

  steps:
  - uses: actions/checkout@v3
  - name: Build
    run: |
      cd richard-test
      cargo build --verbose
    shell: bash
  - name: Install and run my crate
    run: |
      cd richard-test
      cargo install richard-test
      richard-test
    shell: bash
